yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/del/', views.post_del, name='post_del'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path(
        'posts/edit_comment/<int:comment_id>/',
        views.edit_comment,
        name='edit_comment'
    ),
    path(
        'posts/del_comment/<int:comment_id>/',
        views.del_comment,
        name='del_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView, PasswordResetView,)
from django.urls import path

from .views import ProfileEditView, SignUp

app_name = 'users'
urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset_form/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'profile_edit/',
        ProfileEditView.as_view(
            template_name='users/edit_profile_page.html'
        ),
        name='profile_edit'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/includes/generic_form.html
{% load user_filters %}
{% for field in form %} 
<div class="form-group row my-3">
  <label for="{{ field.id_for_label }}">
    {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
  </label>
  {{ field|addclass:"form-control" }} 
    {% if field.help_text %}
      <small 
          id="{{ field.id_for_label }}-help"
          class="form-text text-muted"
      >
        {{ field.help_text|safe }}
      </small>
    {% endif %}
</div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
    <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    <span style="color:red">Ya</span>tube</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item dropdown">
          <span class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Пользователь: <b style="color: black">{{ user.username }}</b></span>
          <ul class="dropdown-menu">
            <li class="dropdown-item">
              <a class="nav-link {% if view_name == 'users:password_change_form' %}active{% endif %}" href="{% url 'users:password_change_form' %}">Изменить пароль</a>
            </li>
            <li class="dropdown-item">
              <a class="nav-link {% if view_name == 'users:profile_edit' %}active{% endif %}" href="{% url 'users:profile_edit' %}">Редактировать профиль</a>
            </li>
            <li class="dropdown-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
            </li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </div>
</nav>

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
<div class="row my-3">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a 
        class="nav-link {% if index %}active{% endif %}"
        href="{% url 'posts:index' %}"
      >
        Все авторы
      </a>
    </li>
    <li class="nav-item">
      <a 
         class="nav-link {% if follow %}active{% endif %}"
         href="{% url 'posts:follow_index' %}"
      >
        Избранные авторы
      </a>
    </li>
  </ul>
</div>
{% endif %}