yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/del/', views.post_del, name='post_del'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path(
        'posts/edit_comment/<int:comment_id>/',
        views.edit_comment,
        name='edit_comment'
    ),
    path(
        'posts/del_comment/<int:comment_id>/',
        views.del_comment,
        name='del_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        "group name",
        max_length=200,
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Код группы'
    )
    description = models.TextField(
        verbose_name='Описание группы'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='group',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Коментарии'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор коментария'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name="Подписчик",
        on_delete=models.CASCADE,
        related_name="follower"
    )
    author = models.ForeignKey(
        User,
        verbose_name="Автор",
        on_delete=models.CASCADE,
        related_name="following"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"],
                name="unique_follow"
            ),
            models.CheckConstraint(
                check=~models.Q(user=models.F("author")),
                name="prevent_self_follow",
            ),
        ]

    def __str__(self):
        return f"{self.user} follows {self.author}"

yatube/posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        exclude = ('author',)
        help_texts = {
            'text': ('Текст'),
            'group': ('Группа'),
            'author': ('Автор'),
            'image': ('Картинка'),
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_text = {
            'text': 'Здесь можно написать комментарий',
        }

yatube/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Group, User, Follow, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from yatube.settings import POSTS_PER_PAGE


def paginator(page_number, posts):
    """Вспомогательная функция для паджинатора."""
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    """Главная страница."""
    template = 'posts/index.html'
    posts = Post.objects.all()
    context = {
        'page_obj': paginator(request.GET.get('page'), posts),
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Страница постов группы."""
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': paginator(request.GET.get('page'), posts),
    }
    return render(request, template, context)


def profile(request, username):
    """Страница пользователя."""
    author = get_object_or_404(
        User.objects.select_related('profile'), username=username)
    posts = author.posts.all()
    template = 'posts/profile.html'
    context = {
        'author': author,
        'posts': posts,
        'page_obj': paginator(request.GET.get('page'), posts),
    }
    return render(request, template, context)


def post_detail(request, post_id):
    """Информация о посте."""
    form = CommentForm(request.POST or None)
    page_obj = get_object_or_404(Post, id=post_id)
    comments = page_obj.comments.all()
    template = 'posts/post_detail.html'
    context = {
        'page_obj': page_obj,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    """Создание поста."""
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    """Редактирование поста."""
    template = 'posts/create_post.html'
    post = get_object_or_404(Post.objects.select_related('author'), pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.id)
    context = {
        'is_edit': True,
        'form': form,
        'post': post
    }
    return render(request, template, context)


@login_required
def post_del(request, post_id):
    """Удаление поста."""
    post = get_object_or_404(Post, pk=post_id)
    if request.user.pk != post.author.pk:
        return redirect('posts:index')
    post.delete()
    return redirect('posts:index')


@login_required
def add_comment(request, post_id):
    """Создание комментария к посту."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def edit_comment(request, comment_id):
    """Редактирование коммента."""
    template = 'posts/edit_comment.html'
    comment = get_object_or_404(
        Comment.objects.select_related('author'), pk=comment_id
    )
    if request.user.pk != comment.author.pk:
        return redirect('posts:post_detail', comment.post.pk)
    form = CommentForm(
        instance=comment,
        data=request.POST or None,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', comment.post.pk)
    context = {
        'form': form,
        'title': 'Редактировать коммент'
    }
    return render(request, template, context)


@login_required
def del_comment(request, comment_id):
    """Удаление коммента."""
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user.pk != comment.author.pk:
        return redirect('posts:post_detail', comment.post.pk)
    comment.delete()
    return redirect('posts:post_detail', comment.post.pk)


@login_required
def follow_index(request):
    """Подписки пользователя."""
    template = 'posts/follow.html'
    posts = Post.objects.filter(author__following__user=request.user)
    context = {
        'page_obj': paginator(request.GET.get('page'), posts),
        'title': 'Подписки'
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Подписка на автора."""
    user = request.user
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=user, author=author)
    if user != author and not is_follower.exists():
        Follow.objects.create(user=user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    """Отписка от автора."""
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    is_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if is_edit %}Редактировать пост{% else %}Новый пост{% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data" action="{% if is_edit %}{% url 'posts:post_edit' form.instance.pk %}{% else %}{% url 'posts:post_create' %}{% endif %}">
          {% csrf_token %}
          {% include 'includes/generic_form.html' %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/edit_comment.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Редактировать коммент к посту <b>{{ form.instance.post.author.get_full_name }}</b></div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data" action="{% url 'posts:edit_comment' form.instance.pk %}">
          {% csrf_token %}
          {% include 'includes/generic_form.html' %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">Сохранить</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}
<title href="{% url 'posts:index' %}">Подписки</title>
{% endblock %}
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% include 'includes/switcher.html' %}
        {% for post in page_obj %}
        <ul>
          <li>
            <a href="{% url 'posts:profile' post.author %}">Автор: {{ post.author.get_full_name }}</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <a href="{% url 'posts:post_detail' post.id %}"> Подробнее:
          </a>
        </ul>
        <article class="col-12 col-md-3">
          {% thumbnail post.image "500x400" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
        </article>
          <p>
          {{ post.text }}
          </p>
        {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      {% endblock %}
    </main>
  </body>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}Записи сообщества{{ group.title }}{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <ul>
      <li>Автор: {{ post.author.get_full_name }}
      </li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
      <a href="{% url 'posts:post_detail' post.id %}"> Подробнее:
      </a>
    </ul>
    <article class="col-12 col-md-3">
      {% thumbnail post.image "500x400" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    </article>
    <p>{{ post.text }}</p>
    {% if not forloop.last %}<hr>{% endif %}
    {% empty %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% load static %}
{% block title %}Последние обновления на сайте{% endblock %}
<body>
  <header>
    {% include 'includes/header.html' %}
  </header>
  <main>
{% block content %}
{% include 'includes/switcher.html' %}
{% cache 20 index_page %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      <a href="{% url 'posts:post_detail' post.id %}"> Подробнее:
      </a>
    </ul>
    <article class="col-12 col-md-3">
      {% thumbnail post.image "500x400" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    </article>
    <p>{{ post.text }}</p> 
    {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы{{post.group.title}}</a>
    {% endif %}  
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endcache %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}
  </main>
</body>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Пост  {{ post.text|slice:":30" }} {% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Дата публикации: {{ page_obj.pub_date }}</li>
      {% if page_obj.group.slug %}
        <li class="list-group-item">
          Группа: {{ page_obj.group.title }}
          <a href="{% url 'posts:group_list' page_obj.group.slug %}">все записи группы</a>
        </li>
      {% endif %}
      <li class="list-group-item">
        Автор: <a href="{% url 'posts:profile' page_obj.author.username %}">{{ page_obj.author.get_full_name }}</a>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: <span>{{ page_obj.author.posts.count }}</span>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ page_obj.text|linebreaksbr }}</p>
  {% if page_obj.author.username == user.username %}
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <p>
      <button class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal">Удалить</button>
    </p>
    <p>
      <a class="btn btn-primary" href="{% url 'posts:post_edit' page_obj.id %}">Pедактировать запись</a>
    </p>
  {% endif %}
  {% include 'posts/includes/comments_form.html' %}
  </article>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author }} </h1>
        <h3>Всего постов: {{posts.count}} </h3>
        {% if author != request.user %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}"
            role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
        {% endif %}
        <article>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author }}</a>
              <a href={% url 'posts:profile' post.author %}>все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
            {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
        </article>       
          {% if post.group.slug %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            <article class="col-12 col-md-3">
              {% thumbnail post.image "500x400" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
            </article>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}      
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}  
{% endblock %}